
import { Language, Goal, ActivityLevel } from './types';

export const TRANSLATIONS = {
  [Language.RU]: {
    welcome: 'Добро пожаловать',
    profile: 'Профиль',
    workout: 'Тренировки',
    nutrition: 'Питание',
    settings: 'Настройки',
    name: 'Имя',
    age: 'Возраст',
    height: 'Рост (см)',
    weight: 'Вес (кг)',
    goal: 'Цель',
    goals: {
      [Goal.LOSE_WEIGHT]: 'Похудение',
      [Goal.MAINTAIN]: 'Удержание веса',
      [Goal.GAIN_MUSCLE]: 'Набор массы',
    },
    activityLevel: 'Активность',
    activityLevels: {
      [ActivityLevel.SEDENTARY]: 'Низкая активность',
      [ActivityLevel.MODERATE]: 'Средняя активность',
      [ActivityLevel.ACTIVE]: 'Высокая активность',
    },
    save: 'Сохранить',
    cancel: 'Отмена',
    add: 'Добавить',
    edit: 'Изменить',
    delete: 'Удалить',
    calories: 'Ккал',
    protein: 'Белки',
    fats: 'Жиры',
    carbs: 'Углеводы',
    total: 'Итого',
    today: 'Сегодня',
    noMeals: 'Приемов пищи пока нет',
    noWorkouts: 'Тренировок пока нет',
    addMeal: 'Добавить прием пищи',
    editMeal: 'Редактировать прием пищи',
    addWorkout: 'Добавить тренировку',
    workoutName: 'Название тренировки (например, День ног)',
    exerciseName: 'Название упражнения',
    addExercise: 'Добавить упражнение',
    finishWorkout: 'Завершить тренировку',
    sets: 'Подходы',
    reps: 'Повторения',
    weightLbsKg: 'Вес (кг)',
    language: 'Язык',
    theme: 'Тема',
    light: 'Светлая',
    dark: 'Темная',
    onboardingTitle: 'Давайте познакомимся!',
    onboardingSubtitle: 'Заполните данные для персонализации.',
    aiCoach: 'AI Тренер',
    aiAnalyze: 'Анализ прогресса',
    analyzing: 'Думаю...',
    mealName: 'Название еды',
    confirmDelete: 'Вы уверены?',
    setNutritionGoal: 'Установите цель по питанию',
    dailyGoal: 'Цель на день',
    exercisesList: 'Список упражнений',
    noExercisesAdded: 'Упражнения еще не добавлены',
    dailyTracker: 'Дневная активность',
    water: 'Вода',
    liters: 'л',
    addWater: 'Добавить воду',
    setWorkoutGoal: 'Цель тренировок',
    monthlyGoal: 'Цель на месяц',
    workoutsThisMonth: 'В этом месяце',
    targetWorkouts: 'Кол-во тренировок',
  },
  [Language.EN]: {
    welcome: 'Welcome',
    profile: 'Profile',
    workout: 'Workouts',
    nutrition: 'Nutrition',
    settings: 'Settings',
    name: 'Name',
    age: 'Age',
    height: 'Height (cm)',
    weight: 'Weight (kg)',
    goal: 'Goal',
    goals: {
      [Goal.LOSE_WEIGHT]: 'Lose Weight',
      [Goal.MAINTAIN]: 'Maintain Weight',
      [Goal.GAIN_MUSCLE]: 'Gain Muscle',
    },
    activityLevel: 'Activity Level',
    activityLevels: {
      [ActivityLevel.SEDENTARY]: 'Low Activity',
      [ActivityLevel.MODERATE]: 'Moderate',
      [ActivityLevel.ACTIVE]: 'Active',
    },
    save: 'Save',
    cancel: 'Cancel',
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    calories: 'Kcal',
    protein: 'Protein',
    fats: 'Fats',
    carbs: 'Carbs',
    total: 'Total',
    today: 'Today',
    noMeals: 'No meals logged yet',
    noWorkouts: 'No workouts logged yet',
    addMeal: 'Add Meal',
    editMeal: 'Edit Meal',
    addWorkout: 'Add Workout',
    workoutName: 'Workout Name (e.g. Leg Day)',
    exerciseName: 'Exercise Name',
    addExercise: 'Add Exercise',
    finishWorkout: 'Finish Workout',
    sets: 'Sets',
    reps: 'Reps',
    weightLbsKg: 'Weight (kg)',
    language: 'Language',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    onboardingTitle: 'Let\'s get started!',
    onboardingSubtitle: 'Fill in your details for personalization.',
    aiCoach: 'AI Coach',
    aiAnalyze: 'Analyze Progress',
    analyzing: 'Thinking...',
    mealName: 'Meal Name',
    confirmDelete: 'Are you sure?',
    setNutritionGoal: 'Set Nutrition Goal',
    dailyGoal: 'Daily Goal',
    exercisesList: 'Exercises List',
    noExercisesAdded: 'No exercises added yet',
    dailyTracker: 'Daily Tracker',
    water: 'Water',
    liters: 'L',
    addWater: 'Add Water',
    setWorkoutGoal: 'Set Workout Goal',
    monthlyGoal: 'Monthly Goal',
    workoutsThisMonth: 'This Month',
    targetWorkouts: 'Target Workouts',
  }
};
